stages:        
  - copy
  - permissions

copy-job: 
    stage: copy
    tags:
        - tio-mon-extension
    script:
    - echo "Compiling the code..."
    - echo "Compile complete."

config-permissions-job:   
    stage: permissions  
    tags:
    - tio-mon-extension
    script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

